all:
	nvcc -I /home/spolisetty/OCC-GNN/3rdparty/thrust -I /home/spolisetty/OCC-GNN/3rdparty/thrust/dependencies/cub/  -I /home/spolisetty/OCC-GNN/3rdparty/thrust/dependencies/libcudacxx/include/ thrust.cu 

